# ==============================================================================
# LINUX PLATFORM OVERRIDES
# ==============================================================================
# Loaded automatically via platform.conf symlink (created by install.sh)

# Linux keybinds
keybind = ctrl+shift+comma=reload_config
keybind = ctrl+enter=toggle_fullscreen
