unbind C-b
set -g prefix C-Space
set -g default -terminal "rxvt -256color";
set -g mouse on

unbind r
bind r source -file $XDG_CONFIG_HOME/tmux/tmux.conf \; display "Reloaded tmux conf"

unbind v
unbind h
unbind % # Split vertically
unbind '"' # Split horizontally
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"
