set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-copycat'

set-option -g default-shell /bin/zsh
set-option -g default-terminal "screen-256color"
set-option -g focus-events on

unbind C-b
set -g prefix C-Space
#set -g default-terminal "rxvt -256color";
set -g mouse on

unbind r
bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf \; display "Reloaded tmux conf"

unbind v
unbind h
unbind % # Split vertically
unbind '"' # Split horizontally

bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

## pane colors
## set active-inactive window styles
#set -g window-style 'fg=colour247,bg=colour236'
#set -g window-active-style 'fg=default,bg=colour234'
#
## Pane border
#set -g pane-border-style bg=default
#set -g pane-border-style fg=colour238
#
## Active pane border
#set -g pane-active-border-style bg=default
#set -g pane-active-border-style fg=blue
#
set -g history-limit 10000
#
set -s escape-time 0

#  modes
setw -g clock-mode-colour colour5
setw -g mode-style 'fg=colour1 bg=colour18 bold'

# panes
set -g pane-border-style 'fg=colour19 bg=colour0'
set -g pane-active-border-style 'bg=colour0 fg=colour9'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'bg=colour235 fg=colour137 dim'
set -g status-left ''
set -g status-right '#[fg=colour233,bg=colour238] %d/%m #[fg=colour233,bg=colour8] %H:%M:%S '
set -g status-right-length 50
set -g status-left-length 20

setw -g window-status-current-style 'fg=colour24 bg=colour242 bold'
setw -g window-status-current-format ' #I#[fg=colour239]:#[fg=colour238]#W#[fg=colour239]#F '

setw -g window-status-style 'fg=colour1 bg=colour236'
setw -g window-status-format ' #I#[fg=colour247]:#[fg=colour250]#W#[fg=colour244]#F '

setw -g window-status-bell-style 'fg=colour255 bg=colour1 bold'

# messages
set -g message-style 'fg=colour184 bg=colour16 bold'

# run this command at the bottom!
run '~/.config/tmux/plugins/tpm/tpm'
