# Interactive shell configuration.

bindkey -v
bindkey -M viins 'kj' vi-cmd-mode
export KEYTIMEOUT=20

zle-keymap-select() {
  if [[ $KEYMAP == vicmd ]]; then
    echo -ne '\e[2 q'
  else
    echo -ne '\e[6 q'
  fi
}
zle -N zle-keymap-select

zle-line-init() { echo -ne '\e[6 q' }
zle -N zle-line-init

autoload -Uz vcs_info add-zsh-hook
add-zsh-hook precmd vcs_info
setopt prompt_subst
PROMPT='%F{green}%~%f ${vcs_info_msg_0_}%# '
RPROMPT='%F{8}%*%f'
zstyle ':vcs_info:git:*' formats '%F{yellow}(%b)%f '

# Rebuild completion metadata once per day; use the cache otherwise.
autoload -Uz compinit
typeset -a stale_compdump
stale_compdump=(~/.zcompdump(N.mh+24))
if [[ ! -f ~/.zcompdump ]] || (( ${#stale_compdump} > 0 )); then
  compinit
else
  compinit -C
fi
unset stale_compdump
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' menu select

HISTFILE=~/.zsh_history
HISTSIZE=50000
SAVEHIST=50000
setopt hist_ignore_dups
setopt hist_find_no_dups
setopt hist_ignore_space
setopt hist_reduce_blanks
setopt share_history
setopt append_history
setopt AUTO_CD

if ls --color=auto / &>/dev/null; then
  alias la="ls -lah --color"
else
  alias la="ls -lahG"
fi

ddg() { w3m "https://html.duckduckgo.com/html/?q=$(echo "$*" | sed 's/ /+/g')"; }
export PYTHONDONTWRITEBYTECODE=1

[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
[[ -f "$HOME/.cargo/env" ]] && . "$HOME/.cargo/env"

# Defer nvm's startup cost until a Node command is used.
if [[ -d "$HOME/.nvm" ]]; then
  export NVM_DIR="$HOME/.nvm"
  lazy_load_nvm() {
    unset -f nvm node npm npx
    [[ -s "$NVM_DIR/nvm.sh" ]] && . "$NVM_DIR/nvm.sh"
  }
  nvm() { lazy_load_nvm; nvm "$@"; }
  node() { lazy_load_nvm; node "$@"; }
  npm() { lazy_load_nvm; npm "$@"; }
  npx() { lazy_load_nvm; npx "$@"; }
fi

[[ ":$PATH:" != *":$HOME/.dual-graph:"* ]] && export PATH="$PATH:$HOME/.dual-graph"

if [[ -d "$HOME/.lmstudio/bin" && ":$PATH:" != *":$HOME/.lmstudio/bin:"* ]]; then
  export PATH="$PATH:$HOME/.lmstudio/bin"
fi
